### ISSUE TITLE
Raster diff with deck.gl-raster

### ISSUE THREAD

**Issue by lukecoursey** [kylebarron/deck.gl-raster#135]
Hi - i'm trying to understand possible use cases of this library and this in particular is one that i'm looking for client side solutions for. Let's say I have two simple single band rasters A and B both as a tiled source (currently in mapbox), could the library render a difference of B minus A to show the pixel-by-pixel change between the two?

**Comment by kylebarron** [comment]
This library isn't getting much maintenance at the moment, but you could do that by using a shader module to subtract one from the other

**Comment by lukecoursey** [comment]
Since I posted I've managed to get something vaguely working, still plenty to figure out but it's looking promising. Thanks a lot for your work on this library, has so much potential!
