### ISSUE TITLE
Mask layer by multipolygon

### ISSUE THREAD

**Issue by d1ken** [kylebarron/deck.gl-raster#46]
Hello.
Your project is awesome.
I hope you will made index (NDVI) picking.
But I need more one feature.
I would like to mask resulted or sourced layer by multipolygon.
Polygons represents my area of interest and I would like to hide not interested for me area.

**Comment by kylebarron** [comment]
Picking is in #32, masking is in #7. If I implement masking, however, it would only be for a bitmap, and you'd have to rasterize polygons yourself.
