### ISSUE TITLE
Module to mask image

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/deck.gl-raster#7]
would be the best fallback
![image](https://user-images.githubusercontent.com/15164633/79719949-dfd4dd80-829c-11ea-89cf-11690cdca481.png)

**Comment by kylebarron** [comment]
Use a bitmap mask, and if "true" `discard` the image pixels at that location.

**Comment by d1ken** [comment]
I found I can use alpha channel of PNG tiles for this purpose?
BitmapLayer support alpha channel and default transparentColor is [0,0,0,0].
How does RasterLayer handle alpha channel?
I mead what will be if part of RGBA image will be [0,0,0,0] color?

**Comment by kylebarron** [comment]
I'm not sure I understand you. Yes PNGs can have an alpha channel, but until this issue is resolved the alpha channel isn't used.
